server:
  port: 8101

spring:
  application:
    name: oj-backend-gateway #以微服务注册进consul或nacos服务列表内
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: oj-backend-user  #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://oj-backend-user               #匹配后提供服务的路由地址
          predicates:
            - Path=/api/user/**
        - id: oj-backend-question  #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://oj-backend-question                #匹配后提供服务的路由地址
          predicates:
            - Path=/api/question/**
        - id: oj-backend-judge  #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://oj-backend-judge                #匹配后提供服务的路由地址
          predicates:
            - Path=/api/judge/**
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2